Include a server-side response
cloudflare/odoh-go pull request #11
Opened 2021-02-23 14:47 UTC by chris-wood

See [the corresponding draft change](https://github.com/tfpauly/draft-pauly-adaptive-dns-privacy/pull/169).

2021-02-24 06:02 UTC, tfpauly commented
Verified interop with my client. Ship it!

2021-03-01 21:49 UTC, tanyav2 approved these changes

2021-03-01 22:43 UTC, tanyav2 requested changes
Reverting approval for now, there is an interop issue that I'm investigating

2021-03-02 00:44 UTC, tanyav2 approved these changes

2021-03-02 01:29 UTC, merged